"""init categoria, subcategoria e produtos

Revision ID: 4fe10c85f5bf
Revises: c20389ee195b
Create Date: 2025-04-29 23:30:58.105037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fe10c85f5bf'
down_revision: Union[str, None] = 'c20389ee195b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('preco', sa.Float(), nullable=False))
    op.add_column('produtos', sa.Column('categoria_id', sa.Integer(), nullable=True))
    op.alter_column('produtos', 'subcategoria_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('produtos', 'dimensao',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('produtos', 'peso',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.drop_constraint(None, 'produtos', type_='foreignkey')
    op.drop_column('produtos', 'id_fabricante')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('id_fabricante', sa.VARCHAR(), nullable=False))
    op.create_foreign_key(None, 'produtos', 'subcategorias', ['subcategoria_id'], ['id'])
    op.alter_column('produtos', 'peso',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('produtos', 'dimensao',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('produtos', 'subcategoria_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('produtos', 'categoria_id')
    op.drop_column('produtos', 'preco')
    # ### end Alembic commands ###
