"""modificar tabela n_0001

Revision ID: ad49988aabeb
Revises: fee403f43565
Create Date: 2025-04-28 23:24:08.453671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad49988aabeb'
down_revision: Union[str, None] = 'fee403f43565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('peso', sa.Float(), nullable=False))
    op.add_column('produtos', sa.Column('dimensao', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'dimensao')
    op.drop_column('produtos', 'peso')
    # ### end Alembic commands ###
